// eslint-disable-next-line import/prefer-default-export
export enum CertificateType {
  "STAKE_KEY_REG" = 0,
  "STAKE_KEY_DE_REG" = 1,
  "STAKE_DELEGATION" = 2,
  "POOL_REG" = 3,
  "POOL_DE_REG" = 4,
  "GENESIS_DELEGATION" = 5,
  "INSTANT_REWARD" = 6,
  "STAKE_REG" = 7,
  "STAKE_DE_REG" = 8,
  "VOTE_DELEG" = 9,
  "STAKE_VOTE_DELEG" = 10,
  "STAKE_REG_DELEG" = 11,
  "VOTE_REG_DELEG" = 12,
  "STAKE_VOTE_REG_DELEG" = 13,
  "COMMITTEE_AUTH_HOT" = 14,
  "COMMITTEE_RESIGN_COLD" = 15,
  "DREP_REG" = 16,
  "DREP_DE_REG" = 17,
  "DREP_UPDATE" = 18, 
}
